### ISSUE TITLE
Bootstrap away from httr OAuth implementation

### ISSUE THREAD

**Issue by Hong-Revo** [cloudyr/AzureAuth#1]
Increasingly messy, we don't use some of it anyway (caching), and Hadley is looking towards httr2.

**Comment by MarkEdmondson1234** [comment]
Nice to see the auth separated out - may I ask what you mean by messy?  

I've found it very useful to have function factories that embed Google auth within them so users can make Google APIs with authenticated calls easily themselves, is that something that is possible with this library too?

**Comment by Hong-Revo** [comment]
I've actually made a few changes to the class:

- New auth methods, device_code and resource_owner
- Reimplement caching, so that the tokens are saved in a custom dir using the rappdirs package

Hacking the class to support these has become rather painful. There's also some Azure features I want to support:

- Certificates
- Azure has 2 distinct schemes for tokens, called "v1.0" and "v2.0" with distinct endpoints and features (v2 is not just a superset of v1)

I think at this point it would be easier just to reimplement everything, keeping only the specific bits I need from httr. I'll still keep the basic structure using R6 classes, and keep the UI the same, for backward compatibility.

**Comment by Hong-Revo** [comment]
I'm not sure what you mean by function factory, but with the AzureToken class it would work like this:

```r
# obtain a token: an R6 object of class 'AzureToken'
token <- get_azure_token("resource", "tenantid", "appid", ...)

# save it
saveRDS(token, "token.RDS")

# load it as required
token <- readRDS("token.RDS")

# refresh when it expires
if(!token$validate()) {
    token$refresh()
}
```

The package will also handle stuff like loading cached tokens rather than needing you to reauthenticate every session.
