### ISSUE TITLE
Support B2C logins

### ISSUE THREAD

**Issue by Hong-Revo** [cloudyr/AzureAuth#11]
Example OAuth URLs courtesy @stephlocke :
```
"https://nightingalehq.b2clogin.com/tfp/nightingalehq.onmicrosoft.com/B2C_1_SignUpAndSignIn/oauth2/v2.0/authorize"
"https://nightingalehq.b2clogin.com/tfp/nightingalehq.onmicrosoft.com/B2C_1_SignUpAndSignIn/oauth2/v2.0/token"
```

**Comment by Hong-Revo** [comment]
@stephlocke, can you try the latest build and see if it works?

**Comment by stephlocke** [comment]
So the URLs so do have a misunderstanding on my part. These should be:
"https://nightingalehq.b2clogin.com/nightingalehq.onmicrosoft.com/oauth2/v2.0/authorize?p=B2C_1_SignUpAndSignIn"
"https://nightingalehq.b2clogin.com/nightingalehq.onmicrosoft.com/oauth2/v2.0/token"

I'll give the new code a go :)

**Comment by Hong-Revo** [comment]
Leave out the `authorize` and `token` parts. I'm not sure how to handle query parameters yet.

**Comment by stephlocke** [comment]
```
library(AzureAuth)
get_azure_token("openid", 
                tenant="nightingalehq", app="lddemo", 
                password="0e490a89-b382-4d3b-9f6b-60630dfd624b",
                aad_host="https://nightingalehq.b2clogin.com/nightingalehq.onmicrosoft.com/oauth2/v2.0",
                version=2)
```
>No encoding supplied: defaulting to UTF-8.
Error in process_aad_response(res) : 
  Not Found (HTTP 404). Failed to obtain Azure Active Directory token. Message:
.

**Comment by Hong-Revo** [comment]
No, you specify the exact URL from before:

https://https://nightingalehq.b2clogin.com/tfp/nightingalehq.onmicrosoft.com/B2C_1_SignUpAndSignIn/oauth2/v2.0

**Comment by stephlocke** [comment]
```
> library(AzureAuth)
> get_azure_token("openid", 
+                 tenant="nightingalehq", app="0e490a89-b382-4d3b-9f6b-60630dfd624b",
+                 aad_host="https://nightingalehq.b2clogin.com/tfp/nightingalehq.onmicrosoft.com/B2C_1_SignUpAndSignIn/oauth2/v2.0",
+                 version=2,
+                 authorize_args=list(redirect_uri="https://localhost:1410")
+ )
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
ERROR: [_parse_http_data] invalid HTTP method
```

I get a redirect that generates a url `https://localhost:1410/?state=ywkdztxsciunebjlqaov&code=eyJraWQiOiJjcGltY29yZV8wOTI1MjAxNSIsInZlciI6IjEuMCIsInp...` but then I'm getting lots of the `ERROR...` lines in the console

**Comment by Hong-Revo** [comment]
Ok, that means the redirect worked, but httpuv is unable to make sense of it for some reason.

I'll see if I can make an account and try logging in myself.

**Comment by stephlocke** [comment]
Yep, you should be able to create an account on the domain.

**Comment by Hong-Revo** [comment]
This is the error URL I get when trying it:

```
https://localhost:1410/?
error=redirect_uri_mismatch&
error_description=AADB2C90006%3a+
The+redirect+URI+%27http%3a%2f%2flocalhost%3a1410%2f%27+provided+in+the+request+is+not+registered+for+the+client+id
```

Is your app setup to allow `https://localhost:1410` as a redirect? Note that it's https, not http.

**Comment by Hong-Revo** [comment]
Cancel that, I added in the `redirect_uri` option and now I get a different problem: the server can't find my account.

Do I "register as a partner" on the nightingale.ai site?

**Comment by stephlocke** [comment]
On the login page you get taken to you during authentication you should be able to trigger an account creation step. This is a pure demo/test AAD so don't worry about messing anything up :)

**Comment by Hong-Revo** [comment]
Ok, I got to the redirect URI. Do you see something like this in your browser?

![image](https://user-images.githubusercontent.com/11328890/57027661-59d11880-6c80-11e9-8876-04c1172d3485.png)

So I think AzureAuth is working, but there's a problem with https certs somewhere. Can you try changing it to a http redirect?

**Comment by stephlocke** [comment]
Unfortunately, the validation on the B2C app side of things only lets us use https addresses

**Comment by Hong-Revo** [comment]
Yea, possible. Maybe try getting a real cert -- you should be able to get one for free from [Let's Encrypt](https://letsencrypt.com).

**Comment by stephlocke** [comment]
Huh, I didn't think you get a LE for localhost because it's not "owned" by anyone, will take a look now

**Comment by Hong-Revo** [comment]
I also tried the httr login function from your email, and it gave the same error.

**Comment by Hong-Revo** [comment]
The other possibility is to change the redirect to https://127.0.0.1 rather than localhost. According to that letsencrypt page, the browser should be able to detect that it's local.

**Comment by stephlocke** [comment]
Changed the redirect to https://127.0.0.1:1410/ but no change in outcome

**Comment by Hong-Revo** [comment]
Ok, actually, can you change it back? I've created a self-signed cert for localhost. I suspect it'll still fail but let's try it anyway.

**Comment by stephlocke** [comment]
Redirect changed

**Comment by Hong-Revo** [comment]
Yeah, no joy. I've raised an issue at the httpuv repo. Maybe try contacting tech support -- they may be able to let you use a http redirect.

**Comment by Hong-Revo** [comment]
So, httpuv doesn't support https. Until/unless they change their mind, or you can set a http redirect, I don't think there's much more I can do.

The other alternative is to enable one of the other authentication flows, eg device_code and/or resource_owner. That will negate the requirement to run httpuv.

**Comment by stephlocke** [comment]
Looks like the https is due to the root libuv folks https://github.com/libuv/libuv/issues/1128

I'll take a look at the other options but it's difficult because this *has* to integrate into a shiny app that will need to go on ssl, not just for this but for general good practice. It's so bizarre when things aren't ssl compliant.

**Comment by Hong-Revo** [comment]
I'll see if there's any alternatives to httpuv. Other than that, everything appears to be working as intended....

**Comment by stephlocke** [comment]
Indeed and it's perfectly reasonable to expect a redirect to https. We're looking at whether the openid connect protocols can incorporate into shinyproxy and I need to check out the oob options some more to see if they can be used - the restriction to working inside a shiny app is a doozy!

**Comment by Hong-Revo** [comment]
#14 for https issue
