### ISSUE TITLE
Activate Travis

### ISSUE THREAD

**Issue by Hong-Revo** [cloudyr/AzureAuth#4]
@MarkEdmondson1234 sorry to bother you again, but I can't seem to get Travis working.

On travis.org the repo is deactivated, and I don't have the option to activate it:

![image](https://user-images.githubusercontent.com/11328890/52336035-f4420700-2a57-11e9-8e16-906b234cb01b.png)

**Comment by MarkEdmondson1234** [comment]
Ok now?

**Comment by Hong-Revo** [comment]
Yep, thanks.

Not sure why I had to ask for it to be activated, the AzureKusto repo didn't have this problem. I hope this isn't going to be a continuing thing as I add more packages....
